{"name": "test_ct07", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "def test_ct07():\n        webdriver.get(url)\n        editar_evento.caminho(True)\n>       editar_evento.ct_07_editar_evento()\n\ntests\\test_editar_evento.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.page_editar_evento.editarEvento object at 0x000001EF826EE6D0>\n\n    def ct_07_editar_evento(self):\n        try:\n            self.find_element(self.btn_excluir).click()\n            sleep(2)\n            self.find_element(self.confirm_excluir).click()\n            sleep(1)\n            msg = self.espera_mensagem()\n            if msg is True:\n                if self.find_element(self.alert_texto).text.find('Evento excluido com sucesso') > -1:\n                    print('\\n CT_07 sem erros: o evento foi excluído com sucesso')\n                    assert True\n                else:\n                    print(\"\\n [!] CT_07 reportou erro: Não houve exclusão do evento\")\n>                   assert False\nE                   AssertionError\n\npages\\page_editar_evento.py:217: AssertionError"}, "start": 1606182463699, "stop": 1606182475666, "uuid": "d15f9e25-4f9e-49d3-8c6e-d01125d99440", "historyId": "2a389823140a5bf89f58c22d5a91c68a", "testCaseId": "3a30dcb91365c730852f0e8a944ab0c5", "fullName": "tests.test_editar_evento#test_ct07", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_editar_evento"}, {"name": "host", "value": "DESKTOP-NM8JMBK"}, {"name": "thread", "value": "7948-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_editar_evento"}]}